x-airflow-common: &airflow-common
  platform: linux/amd64
  build:
    context: ./hands_on_session/airflow
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Make /opt/airflow importable so "scripts" can be imported from DAGs
    PYTHONPATH: /opt/airflow
    # Airflow connection for your simulation Postgres (Conn Id: simulation_db)
    AIRFLOW_CONN_SIMULATION_DB: postgresql://user:password@simulation_db:5432/simulation
  volumes:
    - ./hands_on_session/airflow/dags:/opt/airflow/dags
    - ./hands_on_session/airflow/logs:/opt/airflow/logs
    - ./hands_on_session/airflow/plugins:/opt/airflow/plugins
    - ./hands_on_session/scripts:/opt/airflow/scripts
    - ./hands_on_session/data:/opt/airflow/data

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  simulation_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simulation
    ports:
      # external 5433 -> container 5432 (inside the network you still use host=simulation_db, port=5432)
      - "5433:5432"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db upgrade && airflow users create --role Admin --username admin --password admin --email admin@example.com --firstname admin --lastname user
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    user: "0:0"